# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28b0964eb3332c2d2a340a7af3c2406e3f684b51d78c74d46f97b8522ee55b6e228b96adef76f44eff888a0c04678a4baf02755263a73c0676d985ba5a8f6a75

test:
  secret_key_base: 012767cd66a782e446cc648030b56d02b529e6e6c88f0ec1bbbe690cc584dfe36d29c1bc2ac54254662b78beacf7b43f8bdd259261272be14c48ea8df445af30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
